baseURL = 'https://thaodang.dev/'
languageCode = 'en-us'
title = "Thao's Notes"
theme = "papermod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    homeInfoParams:
        Title: Hello, I'm Thao Dang
        Content: I keep a development log for some of the project I'm working on, you can find them here

    menu:
        main:
            - identifier: categories
            name: categories
            url: /categories/
            weight: 10
            - identifier: tags
            name: tags
            url: /tags/
            weight: 20
            - identifier: example
            name: example.org
            url: https://example.org
            weight: 30