baseURL: "https://thaodang.dev/"
title: "Thao's Notes"
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
      languageName: "English"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
      menu:
        main:
          - name: Archive
            url: archives
            weight: 5
          - name: Resume
            url: resume/
            weight: 10
          - name: Tags
            url: tags/
            weight: 10

params:
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    outputs:
      home:
        - HTML
        - RSS
        - JSON

    homeInfoParams:
      Title: Hello, I'm Thao Dang
      Content: >
        I keep everything I learing in the world here...
    
    socialIcons:
    - name: github
      url: "https://github.com/sudodt"
    - name: linkedin
      url: "https://www.linkedin.com/in/thao-dang-a62201178/"